name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Detect version
        id: detect_version
        run: |
          version=$(node -p "require('./server/package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: adj90/light-blocks:latest,adj90/light-blocks:${{ steps.detect_version.outputs.version }}
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
